# Area
- name: 'area: post'
  description: ''
  color: '#f4db01'

# Category
- name: 'category: tech'
  description: ''
  color: '#f2edfc'
- name: 'category: life'
  description: ''
  color: '#f2edfc'
- name: 'category: fashion'
  description: ''
  color: '#f2edfc'

# Type
- name: 'type: create'
  description: ''
  color: '#02de0a'
- name: 'type: update'
  description: ''
  color: '#02de0a'

# Priority
- name: 'priority: critical'
  description: ''
  color: '#f4ab01'
- name: 'priority: high'
  description: ''
  color: '#f4ab01'
- name: 'priority: medium'
  description: ''
  color: '#f4ab01'
- name: 'priority: low'
  description: ''
  color: '#f4ab01'
- name: 'priority: not-priority'
  description: ''
  color: '#f4ab01'
